version: 2
updates:
  - package-ecosystem: yarn
    directory: "/" 
    target-branch: "main"
    schedule:
      interval: "weekly"

   - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
